### ISSUE TITLE
Perspective

### ISSUE THREAD

**Issue by loulillelund** [EdDataScienceEES/tutorial-giadaleone99#1]
Hi @giadaleone99 !

Thanks for sharing your tutorial repo with me!

It looks incredible, I think. Indeed, very professional and succinct :) I noticed that, in your master readme file, the different folders such as 'data' are hyperlinked, which I thought was very cool and stood out to me! Not a lot of room for improvement form my perspective, think you've certainly covered the essentials. Though, I like to capitalise my folder titles, which I noticed you haven't done and I was wondering why you have a screenshot of the .Rproj icon? 

Again, very impressive!

Best,
Lucas

**Comment by giadaleone99** [comment]
Hey Lou thanks for that!

Yeah, I've thought about capitalisation, I just keep it in lowercase so it's easier for me to write filepaths etc. And the Rproj icon, I used it in my tutorial to show people where they can click to create a new project! 

I am slighlty worried about another aspect, I am hoping a tutor @EliseGallois @dianakjerome @joffy2 or @IslaMS might be able to clarify here. So I started to create the tutorial I while back with this data that I have been given access to by my supervisor for my dissertation. For some reason I thought it was publicly available data. However, today I found out that is actually not the case, and I was wondering if I would be penalised because of this? For the 'reproducibility' aspect of the tutorial, as the data is not available online, and can only be accessed through my repository.

**Comment by IslaMS** [comment]
Hi @giadaleone99,

Maybe you could actually provide a statement on the availability of the data in your tutorial about why aren't they publicly available and when might they be?  You could maybe turn the not publicly available thing into a bit of a lesson for your tutorial user?  Other options are you make fake data with the same format as your real data and make those fake data public as long as it is clear that they are fake data?  Or you work with a subset of the data if you are allowed to make a subset publicly available.  If the data were produced with funding from the UK government then they do need to be made public at some point unless they are data about people and cannot be made public due to privacy concerns.  Anyhow, I wouldn't worry too much about this, but maybe trying to spin the experience as a learning objective for you and your tutorial user!

Isla

**Comment by giadaleone99** [comment]
Thank you Isla, 

I will probably stick to talking about public data availability rather than making the fake data as I am pretty much done with the tutorial and just making a few final edits.

**Comment by loulillelund** [comment]
Hey @giadaleone99 

Ahh! Okay got you! That makes sense :)

Lucas
